// Bakes the in-pod scripts into the bundle as seed.generated.ts.
//
// The agent pod is not ours - it belongs to the agents extension, and it is made from that
// extension's own seed. What this extension needs in it (the gather, the two shell scripts and
// the report spec) therefore has to travel inside this bundle and be written into the pod at
// the start of every run. Real files under pkg/<name>/seed rather than strings built here, so
// they are linted, syntax-checked and read like the scripts they are.
//
// Run after editing anything under seed/:
//   yarn gen-seed
// The output is committed, so a normal build never runs this.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.join(here, '..', 'pkg', 'interrupt-duty-reports');
const SEED = path.join(PKG, 'seed');
const OUT = path.join(PKG, 'seed.generated.ts');

const files = {};

for (const name of fs.readdirSync(SEED).sort()) {
  const full = path.join(SEED, name);

  if (fs.statSync(full).isFile()) {
    files[name] = fs.readFileSync(full, 'utf8');
  }
}

const body = Object.keys(files)
  .map((name) => `  ${ JSON.stringify(name) }: ${ JSON.stringify(files[name]) },`)
  .join('\n');

fs.writeFileSync(OUT, `/* eslint-disable */
// Generated by scripts/gen-seed.mjs from pkg/interrupt-duty-reports/seed. Do not edit.
export const SEED_FILES: Record<string, string> = {
${ body }
};
`);

const size = Object.values(files).reduce((total, text) => total + Buffer.byteLength(text), 0);

console.log(`seed: ${ Object.keys(files).length } files, ${ (size / 1024).toFixed(1) } KiB -> ${ path.relative(process.cwd(), OUT) }`);
