// Bakes this extension's non-code files into the bundle.
//
// Two kinds, for two reasons that are both "a built UMD bundle cannot fetch a file next to
// itself":
//
//   seed/     the scripts the agent pod runs. The pod is not ours - it belongs to the agents
//             extension and is built from that extension's seed - so what we need in it travels
//             inside this bundle and is written into the pod at the start of every run.
//
//   assets/   the sidebar icon. Rancher renders a product's icon as <img src>, and a built
//             extension is served from a path chosen by whoever installed it, so an emitted
//             file's URL is not something this build gets to know. A data URI has no URL to get
//             wrong.
//
// Real files rather than strings built here, so they are linted, syntax-checked and previewable
// as the scripts and drawings they are. Run after editing either directory:
//   yarn gen-seed
// The output is committed, so a normal build never runs this.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.join(here, '..', 'pkg', 'interrupt-duty-reports-console');
const SEED = path.join(PKG, 'seed');
const ASSETS = path.join(PKG, 'assets');

function generated(body) {
  return `/* eslint-disable */\n// Generated by scripts/gen-seed.mjs. Do not edit.\n${ body }`;
}

// ── The pod's scripts ──────────────────────────────────────────────────────────────────────
const files = {};

for (const name of fs.readdirSync(SEED).sort()) {
  if (fs.statSync(path.join(SEED, name)).isFile()) {
    files[name] = fs.readFileSync(path.join(SEED, name), 'utf8');
  }
}

const seedBody = Object.keys(files)
  .map((name) => `  ${ JSON.stringify(name) }: ${ JSON.stringify(files[name]) },`)
  .join('\n');

fs.writeFileSync(
  path.join(PKG, 'seed.generated.ts'),
  generated(`export const SEED_FILES: Record<string, string> = {\n${ seedBody }\n};\n`),
);

const seedSize = Object.values(files).reduce((total, text) => total + Buffer.byteLength(text), 0);

console.log(`seed:  ${ Object.keys(files).length } files, ${ (seedSize / 1024).toFixed(1) } KiB`);

// ── The sidebar icon ───────────────────────────────────────────────────────────────────────
// base64 rather than percent-encoded utf8: it survives every place a data URI gets copied
// through, and the icon is small enough that the ~33% is nothing.
const navIcon = fs.readFileSync(path.join(ASSETS, 'nav-icon.svg'));
const dataUri = `data:image/svg+xml;base64,${ navIcon.toString('base64') }`;

fs.writeFileSync(
  path.join(PKG, 'icon.generated.ts'),
  generated(`export const NAV_ICON: string = ${ JSON.stringify(dataUri) };\n`),
);

console.log(`icon:  nav-icon.svg, ${ navIcon.length } bytes -> ${ dataUri.length } char data URI`);
