// The two credentials a report needs, stored PER RANCHER USER.
//
// Per user, because a report is generated by somebody and reads Jira and GitHub as them: a
// shared token means everyone's report is fetched with one person's access, and whoever's it is
// cannot tell. Each person brings their own.
//
// It is NOT shared with Extension Studio any more. That extension keeps one `gh_token` for the
// whole installation - its own code calls it "a token written by anybody" - so borrowing it is
// the shared-credential problem wearing a different name. The handling below is still its
// design, because that part was right:
//
//   - **Write-only from the browser.** A credential goes in and never comes back out. Nothing
//     here ever fetches a Secret's `data`.
//   - **`PartialObjectMetadata`.** Asking for that representation gets `metadata` with no `data`
//     and no `stringData` - the only way to learn anything about a Secret from a browser without
//     the browser receiving it. It goes on the writes as much as on the read: a PATCH answers
//     with the whole updated object by default, which is the same leak in the other direction.
//     It has to be the raw apiserver path, because Steve answers in its own shape and ignores
//     the header.
//   - **Merge patches.** A read-modify-PUT would have to fetch the object to preserve the keys
//     it is not touching, which pulls the credential into the page on every save. A patch says
//     what changed; `null` deletes a key.
//   - **An annotation says whether one is stored**, so a form can choose between "Set" and
//     "Replace" without going near `data`.
//
// The token itself is read by the agent pod, with its own ServiceAccount, at the moment a report
// runs. It is never sent from here into the pod, which is what the run used to do.
import { K8S_BASE, rancherFetch } from './rancher';

/** Where this extension keeps its own. The reports live here too. */
export const CRED_NAMESPACE = 'interrupt-duty-reports-console';
export const CRED_SECRET = 'settings';

/** The key prefixes. One key per user: `gh_token-<principal>`, `jira_pat-<principal>`. */
export const GH_TOKEN_KEY = 'gh_token';
export const JIRA_PAT_KEY = 'jira_pat';

/**
 * A Rancher principal as a Secret key.
 *
 * `local://user-qncms` becomes `local-user-qncms`. The principal id is what the dashboard
 * actually has - it is on every page, it is stable, and it distinguishes a local user from the
 * same login arriving through GitHub. Secret data keys allow only `[-._a-zA-Z0-9]`, so
 * everything else collapses to a hyphen.
 */
export function userSlug(principalId: string): string {
  return String(principalId || '')
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 200) || 'unknown';
}

export function ghKey(principalId: string): string {
  return `${ GH_TOKEN_KEY }-${ userSlug(principalId) }`;
}

export function jiraKey(principalId: string): string {
  return `${ JIRA_PAT_KEY }-${ userSlug(principalId) }`;
}

const ghAnnotation = (principalId: string) => `interrupt-duty.rancher.io/gh-${ userSlug(principalId) }`;
const jiraAnnotation = (principalId: string) => `interrupt-duty.rancher.io/jira-${ userSlug(principalId) }`;

/**
 * Ask for metadata and nothing else.
 *
 * `PartialObjectMetadata` is a content negotiation the apiserver does on any object: ask for it
 * and the answer carries `metadata` alone.
 */
const METADATA_ONLY = { Accept: 'application/json;as=PartialObjectMetadata;g=meta.k8s.io;v=v1' };

function secretPath(namespace: string, name: string): string {
  return `${ K8S_BASE }/namespaces/${ namespace }/secrets/${ name }`;
}

async function secretMetadata(namespace: string, name: string): Promise<any | null> {
  const object = await rancherFetch(secretPath(namespace, name), { headers: METADATA_ONLY }).catch(() => null);

  return object?.metadata || null;
}

/**
 * Which keys a Secret holds, without reading any of them.
 *
 * From `managedFields`, which records the field paths each writer owns - so `f:data` lists the
 * key names and none of the values. It is the fallback for a Secret written before the
 * annotation existed, which is every Extension Studio older than the change that added it.
 */
function managedDataKeys(metadata: any): string[] {
  const keys = new Set<string>();

  (metadata?.managedFields || []).forEach((entry: any) => {
    Object.keys(entry?.fieldsV1?.['f:data'] || {}).forEach((field) => {
      if (field.startsWith('f:')) {
        keys.add(field.slice(2));
      }
    });
  });

  return [...keys];
}

export interface CredentialStatus {
  /** Whether THIS user has stored one. Nobody else's presence helps them. */
  gh: boolean;
  jira: boolean;
  /** How many other people have stored a pair, which is worth saying on a shared page. */
  others: number;
  /** True when the namespace or Secret could not be read at all - a permissions problem, not an absence. */
  unreadable: boolean;
}

/** What this user has stored, and nothing about what it is. */
export async function readCredentialStatus(principalId: string): Promise<CredentialStatus> {
  const metadata = await secretMetadata(CRED_NAMESPACE, CRED_SECRET);

  if (!metadata) {
    return {
      gh: false, jira: false, others: 0, unreadable: false,
    };
  }

  const keys = managedDataKeys(metadata);
  const annotations = metadata.annotations || {};
  const has = (key: string, annotation: string) => annotations[annotation] === 'set' || keys.includes(key);
  const gh = has(ghKey(principalId), ghAnnotation(principalId));
  const everyone = new Set([
    ...keys.filter((key) => key.startsWith(`${ GH_TOKEN_KEY }-`)),
    ...Object.keys(annotations)
      .filter((key) => key.startsWith('interrupt-duty.rancher.io/gh-'))
      .map((key) => `${ GH_TOKEN_KEY }-${ key.split('/')[1].replace(/^gh-/, '') }`),
  ]);

  return {
    gh,
    jira:       has(jiraKey(principalId), jiraAnnotation(principalId)),
    others:     Math.max(0, everyone.size - (gh ? 1 : 0)),
    unreadable: false,
  };
}

/** The namespace and an empty Secret, made on the way past so the patch below has something to patch. */
async function ensureSecret(): Promise<void> {
  const existing = await secretMetadata(CRED_NAMESPACE, CRED_SECRET);

  if (existing) {
    return;
  }

  await rancherFetch(`${ K8S_BASE }/namespaces`, {
    method: 'POST',
    body:   JSON.stringify({ apiVersion: 'v1', kind: 'Namespace', metadata: { name: CRED_NAMESPACE } }),
  }).catch((e: any) => {
    if (!/409|already exists|alreadyexists/i.test(e?.message || '')) {
      throw e;
    }
  });

  await rancherFetch(`${ K8S_BASE }/namespaces/${ CRED_NAMESPACE }/secrets`, {
    method:  'POST',
    headers: METADATA_ONLY,
    body:    JSON.stringify({
      apiVersion: 'v1',
      kind:       'Secret',
      type:       'Opaque',
      metadata:   { name: CRED_SECRET, namespace: CRED_NAMESPACE },
    }),
  }).catch((e: any) => {
    if (!/409|already exists|alreadyexists/i.test(e?.message || '')) {
      throw e;
    }
  });
}

/** UTF-8 safe, because btoa alone throws on anything outside latin-1. */
function encodeSecret(value: string): string {
  return btoa(String.fromCharCode(...new TextEncoder().encode(value)));
}

export interface CredentialChanges {
  /** Absent leaves it alone; `''` clears it, which is the only way to remove one. */
  ghToken?: string;
  jiraPat?: string;
}

/**
 * Write only what was touched.
 *
 * A field the form left `undefined` is not in `changes` and is not written, which is what stops
 * opening the dialog and saving from blanking a credential nobody could see.
 */
export async function saveCredentials(principalId: string, changes: CredentialChanges): Promise<void> {
  const data: Record<string, string | null> = {};
  const annotations: Record<string, string | null> = {};

  if (changes.ghToken !== undefined) {
    data[ghKey(principalId)] = changes.ghToken === '' ? null : encodeSecret(changes.ghToken);
    annotations[ghAnnotation(principalId)] = changes.ghToken === '' ? null : 'set';
  }

  if (changes.jiraPat !== undefined) {
    data[jiraKey(principalId)] = changes.jiraPat === '' ? null : encodeSecret(changes.jiraPat);
    annotations[jiraAnnotation(principalId)] = changes.jiraPat === '' ? null : 'set';
  }

  if (!Object.keys(data).length) {
    return;
  }

  await ensureSecret();

  await rancherFetch(secretPath(CRED_NAMESPACE, CRED_SECRET), {
    method:  'PATCH',
    headers: { 'Content-Type': 'application/merge-patch+json', ...METADATA_ONLY },
    body:    JSON.stringify({ metadata: { annotations }, data }),
  });
}

/** Whether this user can start a run: both of their credentials stored. */
export function credentialsReady(status: CredentialStatus): boolean {
  return status.gh && status.jira;
}
